services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_USER=reminders
      - MYSQL_DATABASE=reminders
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
