services:
  db:
    image: mysql:9.0.1
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  reminder:
    image: golang:1.23.1
    env_file:
      - ./.env
    volumes:
      - ./reminder:/root
    working_dir: /root
    command: [ "go", "run", "." ]
    healthcheck:
      test: [ "CMD", "curl", "localhost:8080/healthcheck" ]
      interval: 10m
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
  poller:
    image: golang:1.23.1
    env_file:
      - .env
    volumes:
      - ./poller:/root
    working_dir: /root
    command: [ "go", "run", "." ]
    depends_on:
      reminder:
        condition: service_healthy
  test_mm:
    profiles:
      - test
    image: mattermost/mattermost-preview:10.0.0
    container_name: test_mm
    ports:
      - "8065:8065"
    environment:
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
