services:
  db:
    image: mysql:9.1.0
    container_name: reminder_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  reminder:
    build: ./reminder
    container_name: reminder
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      MM_SC_TOKEN: ${MM_SC_TOKEN}
      DEFAULT_TZ: Asia/Novosibirsk
    depends_on:
      db:
        condition: service_healthy
  poller:
    build: ./poller
    container_name: poller
    environment:
      POLL_PERIOD: 1m
    depends_on:
      reminder:
        condition: service_healthy
  test_mm:
    profiles:
      - test
    image: mattermost/mattermost-preview:10.1.2
    container_name: test_mm
    ports:
      - "8065:8065"
    environment:
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"

volumes:
  data:
    name: reminder_data
