services:
  db:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  reminder:
    image: golang
    env_file:
      - ./.env
    volumes:
      - ./reminder:/root
    working_dir: /root
    command: ["go", "run", "."]
    healthcheck:
      test: [ "CMD", "curl", "localhost:8080/healthcheck" ]
      interval: 10m
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
  poller:
    image: golang
    volumes:
      - ./poller:/root
    working_dir: /root
    command: ["go", "run", "."]
    depends_on:
      reminder:
        condition: service_healthy
  test_mm:
    profiles:
      - test
    image: mattermost/mattermost-preview
    container_name: test_mm
    ports:
    - "8065:8065"
    environment:
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"

