services:
  db:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
