services:
  db:
    image: mysql:9.0.1
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  reminder:
    build: ./reminder
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  poller:
    build: ./poller
    env_file:
      - .env
    depends_on:
      reminder:
        condition: service_healthy
  test_mm:
    profiles:
      - test
    image: mattermost/mattermost-preview:10.0.0
    container_name: test_mm
    ports:
      - "8065:8065"
    environment:
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
